"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-28 23:46:42.738945
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_model", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model", "position", name="uq_model_routes_model_position"),
    )
    with op.batch_alter_table("model_routes", schema=None) as batch_op:
        batch_op.create_index("ix_model_routes_model", ["model"], unique=False)

    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_model", sa.String(length=128), nullable=False),
        sa.Column("input_usd_per_mtok", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("output_usd_per_mtok", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("effective_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_prices_provider_model_effective",
            ["provider", "provider_model", "effective_at"],
            unique=False,
        )

    op.create_table(
        "virtual_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_last4", sa.String(length=4), nullable=False),
        sa.Column("monthly_budget_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("cache_enabled", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "budget_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("spent_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["key_id"],
            ["virtual_keys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_id", "period", name="uq_budget_periods_key_period"),
    )
    op.create_table(
        "cache_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("last_hit_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["key_id"],
            ["virtual_keys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_id", "model", "prompt_hash", name="uq_cache_entries_scope_hash"),
    )
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_cache_entries_scope_created", ["key_id", "model", "created_at"], unique=False
        )

    op.create_table(
        "requests",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("key_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=True),
        sa.Column("provider_model", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("streamed", sa.Boolean(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("tokens_estimated", sa.Boolean(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("price_id", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("ttfb_ms", sa.Integer(), nullable=True),
        sa.Column("redactions", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["key_id"],
            ["virtual_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["prices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.create_index("ix_requests_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_requests_key_created", ["key_id", "created_at"], unique=False)
        batch_op.create_index("ix_requests_status", ["status"], unique=False)

    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=26), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_model", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("status_code", sa.SmallInteger(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["request_id"], ["requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.create_index("ix_attempts_request_id", ["request_id"], unique=False)

    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=26), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["budget_periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    with op.batch_alter_table("reservations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reservations_state_expires", ["state", "expires_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reservations", schema=None) as batch_op:
        batch_op.drop_index("ix_reservations_state_expires")

    op.drop_table("reservations")
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_attempts_request_id")

    op.drop_table("attempts")
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_index("ix_requests_status")
        batch_op.drop_index("ix_requests_key_created")
        batch_op.drop_index("ix_requests_created_at")

    op.drop_table("requests")
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_cache_entries_scope_created")

    op.drop_table("cache_entries")
    op.drop_table("budget_periods")
    op.drop_table("virtual_keys")
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.drop_index("ix_prices_provider_model_effective")

    op.drop_table("prices")
    with op.batch_alter_table("model_routes", schema=None) as batch_op:
        batch_op.drop_index("ix_model_routes_model")

    op.drop_table("model_routes")
    # ### end Alembic commands ###
